included:
  - Sources
  - Tests

excluded:
  - "**/.build"
  - "**/Package.swift"
  - Tests/HeidrunServerKitTests/TestCerts

function_body_length:
  - 599 # warning
  - 666 # error
type_body_length:
  - 888 # warning
  - 3333 # error
file_length:
  - 800 # warning
  - 999 # error
#identifier_name:
#  min_length: 2 # only warning
#  max_length: # warning and error
#    warning: 80
#   error: 100
opt_in_rules:
  - closure_end_indentation
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - implicit_return
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  #- no_extension_access_modifier
  - overridden_super_call
  - pattern_matching_keywords
  - private_subject
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - switch_case_on_newline
  - toggle_bool
  #- trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - weak_delegate
  - yoda_condition
analyzer_rules:
  - unused_declaration
  - unused_import
disabled_rules:
  - trailing_whitespace
  - type_name
  - comment_spacing
  - non_optional_string_data_conversion
  - identifier_name
line_length:
  warning: 666
  error: 700
cyclomatic_complexity:
  warning: 150
  error: 225
function_parameter_count:
  warning: 10
  error: 20
